### ISSUE TITLE
Can't create a peer - Fatal Error 

### ISSUE THREAD

**Issue by maksimyugai** [subutai-io/agent#833] opened 2018-11-07 16:14 UTC
Can't create a peer. Facing with following error. 
I'm trying to create a peer on laptop:
 
_**Configuration**_
![image](https://user-images.githubusercontent.com/6375643/48142669-6a0ec900-e2d7-11e8-8574-14d889d6b2f8.png) 

_**/var/cache/subutai**_
![image](https://user-images.githubusercontent.com/6375643/48142869-d8ec2200-e2d7-11e8-85be-e4723aed9b16.png)

_**vagrant dir right after error:**_
``` kauffman: localpeer $ la
total 20K
drwxr-xr-x 3 kauffman kauffman 4.0K Nov  7 21:40 ./
drwxr-xr-x 3 kauffman kauffman 4.0K Nov  2 21:50 ../
drwxr-xr-x 4 kauffman kauffman 4.0K Nov  3 00:53 .vagrant/
-rw-r--r-- 1 kauffman kauffman 3.0K Nov  2 21:59 Vagrantfile
-rw-r--r-- 1 kauffman kauffman   87 Nov  2 22:01 vagrant-subutai.yml
 kauffman: localpeer $ 
```
_**subutai list i**_
```bash
subutai@subutai:~$ sudo subutai list i -p
NAME    STATE   IP      Interface       PARENT
----    -----   --      ---------       ------
subutai@subutai:~$
```
_**vagrant-subutai.yml**_
```yaml 
SUBUTAI_PEER: true
SUBUTAI_ENV: dev
SUBUTAI_CPU: 2
SUBUTAI_RAM: 4096
SUBUTAI_DISK: 100
```
_**Vagrantfile**_
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "subutai/stretch"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```
_**Logs**_
```  
kauffman: localpeer $ vagrant up                                                                                                                                                                 
Bringing machine 'default' up with 'virtualbox' provider...                                                                                                                                       
==> default: Preparing master VM for linked clones...                                                                                                                                             
    default: This is a one time operation. Once the master VM is prepared,                                                                                                                        
    default: it will be used as a base for linked clones, making the creation                                                                                                                     
    default: of new VMs take milliseconds on a modern system.                                                                                                                                     
==> default: Importing base box 'subutai/stretch'...                                                                                                                                              
==> default: Cloning VM...                                                                                                                                                                        
==> default: Matching MAC address for NAT networking...                                                                                                                                           
==> default: Checking if box 'subutai/stretch' is up to date...                                                                                                                                   
==> default: A newer version of the box 'subutai/stretch' for provider 'virtualbox' is                                                                                                            
==> default: available! You currently have version '7.0.4'. The latest is version                                                                                                                 
==> default: '7.0.7'. Run `vagrant box update` to update.                                                                                                                                         
==> default: Setting the name of the VM: localpeer_default_1541605426855_76255                                                                                                                    
==> default: Clearing any previously set network interfaces...                                                                                                                                    
==> default: Available bridged network interfaces:                                                                                                                                                
1) wlan0                                                                                                                                                                                          
2) br-940b77f68ae4                                                                                                                                                                                
3) eth0                                                                                                                                                                                           
4) br-9818fb1f7959                                                                                                                                                                                
5) veth003792f                                                                                                                                                                                    
6) vethc11afc5                                                                                                                                                                                    
7) docker0                                                                                                                                                                                        
8) veth98687ed                                                                                                                                                                                    
==> default: When choosing an interface, it is usually the one that is                                                                                                                            
==> default: being used to connect to the internet.                                                                                                                                               
    default: Which interface should the network bridge to? 1                                                                                                                                      
==> default: Preparing network interfaces based on configuration...                                                                                                                               
    default: Adapter 1: nat                                                                                                                                                                       
    default: Adapter 2: bridged                                                                                                                                                                   
==> default: Forwarding ports...                                                                                                                                                                  
    default: 8443 (guest) => 9999 (host) (adapter 1)                                                                                                                                              
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: subutai
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
   default: Inserting generated public key within guest...                                                                                                                                       
    default: Removing insecure key from the guest if it's present...                                                                                                                              
    default: Key inserted! Disconnecting and reconnecting using new SSH key...                                                                                                                    
==> default: Machine booted and ready!                                                                                                                                                            
[default] No installation found.                                                                                                                                                                  
Reading package lists...                                                                                                                                                                          
Building dependency tree...                                                                                                                                                                       
Reading state information...                                                                                                                                                                      
dkms is already the newest version (2.3-2).                                                                                                                                                       
dkms set to manually installed.                                                                                                                                                                   
linux-headers-4.9.0-6-amd64 is already the newest version (4.9.88-1+deb9u1).                                                                                                                      
linux-headers-4.9.0-6-amd64 set to manually installed.                                                                                                                                            
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.                                                                                                                                    
Copy iso file /usr/share/virtualbox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso                                                                                               
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.2.20 - guest version is unknown
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.20 Guest Additions for Linux........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.  This may take a while.
update-initramfs: Generating /boot/initrd.img-4.9.0-6-amd64
VirtualBox Guest Additions: Starting.
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/kauffman/peers/localpeer
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20181107-21373-4xhi91.sh
    default: ------------------------------------------------------------------
    default: User Specified Parameters:
    default: ------------------------------------------------------------------
    default: PROVISION                = true
    default: SUBUTAI_PEER             = true
    default: DESIRED_CONSOLE_PORT     = 9999
    default: DESIRED_SSH_PORT         = 4567
    default: SUBUTAI_ENV              = dev
    default: SUBUTAI_RAM              = 4096
    default: SUBUTAI_CPU              = 2
    default: SUBUTAI_DESKTOP          = false                                                                                                                                                     
    default: SUBUTAI_MAN_TMPL         =                                                                                                                                                           
    default: BRIDGE                   =                                                                                                                                                           
    default: AUTHORIZED_KEYS          =                                                                                                                                                           
    default: ------------------------------------------------------------------                                                                                                                   
    default: Run Generated Parameters:                                                                                                                                                            
    default: ------------------------------------------------------------------                                                                                                                   
    default: _CONSOLE_PORT            = 9999                                                                                                                                                      
    default: _BRIDGED                 = true                                                                                                                                                      
    default: _BASE_MAC                = 080027c22e10                                                                                                                                              
    default: _ALT_MANAGEMENT_MD5      =                                                                                                                                                           
    default: _ALT_MANAGEMENT_MD5_LAST =                                                                                                                                                           
    default: _ALT_MANAGEMENT          =                                                                                                                                                           
    default: ----------------------------------------------------------------------------------------------                                                                                       
    default:  Requirements for "rng-tools.service" are handled automatically during Subutai installation.                                                                                         
    default:                    You may ignore failure notices regarding this tool.                                                                                                               
    default: ----------------------------------------------------------------------------------------------                                                                                       
    default: Installing subutai ...
    default: Get:1 http://security.debian.org stretch/updates InRelease [94.3 kB]
    default: Ign:2 http://ftp.de.debian.org/debian stretch InRelease
    default: Get:4 http://ftp.de.debian.org/debian stretch Release [118 kB]
    default: Get:5 http://deb.subutai.io/subutai dev InRelease [2,795 B]
    default: Get:7 http://ftp.de.debian.org/debian stretch Release.gpg [2,434 B]
    default: Get:8 http://deb.subutai.io/subutai dev/main amd64 Packages [3,319 B]
    default: Get:9 http://security.debian.org stretch/updates/non-free Sources [1,216 B]
    default: Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
    default: Get:10 http://security.debian.org stretch/updates/main Sources [184 kB]

.........
 5.44 MiB / 291.79 MiB    1.86% 01m34s
 6.26 MiB / 291.79 MiB    2.15% 01m31s
 7.10 MiB / 291.79 MiB    2.43% 01m28s
 7.82 MiB / 291.79 MiB    2.68% 01m27s
 8.68 MiB / 291.79 MiB    2.97% 01m24s
 9.43 MiB / 291.79 MiB    3.23% 01m24s
 10.24 MiB / 291.79 MiB    3.51% 01m22s
 10.91 MiB / 291.79 MiB    3.74% 01m22s
 11.01 MiB / 291.79 MiB    3.77% 01m26s
 11.63 MiB / 291.79 MiB    3.99% 01m26s
 12.32 MiB / 291.79 MiB    4.22% 01m26s
 12.89 MiB / 291.79 MiB    4.42% 01m26s
 13.43 MiB / 291.79 MiB    4.60% 01m27s
 14.04 MiB / 291.79 MiB    4.81% 01m27s
 14.71 MiB / 291.79 MiB    5.04% 01m26s
 15.10 MiB / 291.79 MiB    5.17% 01m28s
 15.89 MiB / 291.79 MiB    5.45% 01m27s
 16.52 MiB / 291.79 MiB    5.66% 01m26s
 17.21 MiB / 291.79 MiB    5.90% 01m26s
 18.01 MiB / 291.79 MiB    6.17% 01m25s
 18.01 MiB / 291.79 MiB    6.17% 01m25s
 18.01 MiB / 291.79 MiB    6.17% 01m24s
 18.01 MiB / 291.79 MiB    6.17% 01m24s
 18.01 MiB / 291.79 MiB    6.17% 6s
    default: time="2018-11-07 15:46:43" level=info msg="Unpacking template management"
    default: time="2018-11-07 15:46:43" level=fatal msg="Extracting tgz, open /var/cache/subutai/QmTnAnGAVTgUMWZG2zZ4uR6NATH4mnDQbqXadjKgTmwTQM: no such file or directory"
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
And why it used this id: ```QmTnAnGAVTgUMWZG2zZ4uR6NATH4mnDQbqXadjKgTmwTQM```?
Couldn't find template with this id.

**Comment by kamanbaev** [comment] 2018-11-08 12:01
Brought peer up successfully several times with the same parameters as in issue and with different parameters on dev.
Could not reproduce.

**Comment by kurmanbekova6** [comment] 2018-11-08 12:02
Successfully brought peer up  several times with the same parameters as in issue and with different parameters on dev.
Could not reproduce.

**Comment by Dilshat** [comment] 2018-11-08 12:03
closing for now until it happens again

**Comment by etursunbaev** [comment] 2018-11-08 12:03
Note: It seems not an agent issue at all.

**Closed by Dilshat** 2018-11-08 12:03 UTC
